language: python
python:
  - "3.7"

os:
  - linux

install:
    - pip install flake8
    - pip install pytest
    - pip install pytest-cov
    - pip install codecov
    - pip install -r requirements.txt

script:
    - make lint
    - make pytest
    - make coverage


after_success:
    - codecov
